default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PG_DATABASE_NAME"] %>
  password: <%= ENV["PG_DATABASE_PASSWORD"] %>
  timeout: 5000

development:
  <<: *default
  database: master_piece_development

test:
  <<: *default
  database: master_piece_test

production:
  primary: &primary_production
    <<: *default
    database: master_piece_production
    username: master_piece
    password: <%= ENV["MASTER_PIECE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: master_piece_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: master_piece_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: master_piece_production_cable
    migrations_paths: db/cable_migrate
